using ETR.Domain.Enums;

namespace ETR.Application.DTOs;

public record LogbookSummaryResponse(
    int AccountId,
    string UserCode,
    string FullName,
    decimal TotalFlightHours,
    decimal TotalSimulatorHours,
    decimal TotalDualHours,
    decimal FlightDualHours,
    decimal SimulatorDualHours,
    decimal TotalSoloHours,
    decimal TotalPicHours,
    decimal TotalNightHours,
    decimal TotalInstrumentHours,
    decimal FlightInstrumentHours,
    decimal SimulatorInstrumentHours,
    decimal TotalCrossCountryHours,
    int TotalDayLandings,
    int TotalNightLandings,
    int TotalLandings,
    int TotalSignedSessionsCount,
    DateTime? LastFlightDate,
    IReadOnlyList<LogbookEntryDto> Entries,
    string Disclaimer = "Tổng giờ logbook phản ánh thời gian đào tạo thực tế đã được ký nhận, độc lập với đánh giá hoàn thành môn học.");

public record LogbookEntryDto(
    int AttendanceRecordId,
    int SessionId,
    int EnrollmentId,
    string? LessonCode,
    string SessionTitle,
    DateTime? SessionDate,
    TrainingType TrainingType,
    string? Location,
    string? AircraftRegistration,
    string? SimulatorDevice,
    string? DepartureIcao,
    string? ArrivalIcao,
    string? Route,
    decimal FlightHours,
    decimal SimulatorHours,
    decimal DualHours,
    decimal SoloHours,
    decimal PicHours,
    decimal NightHours,
    decimal InstrumentHours,
    decimal CrossCountryHours,
    int DayLandings,
    int NightLandings,
    int TotalLandings,
    string? Remarks,
    string? InstructorComments,
    string? StudentComments,
    DateTime? InstructorSignedAt,
    int? InstructorSignedByAccountId,
    DateTime? StudentSignedAt,
    int? StudentSignedByAccountId);
